//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sCoolMeal2018
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sCoolMealWebDBEntities : DbContext
    {
        public sCoolMealWebDBEntities()
            : base("name=sCoolMealWebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Address> tbl_Address { get; set; }
        public virtual DbSet<tbl_AddressType> tbl_AddressType { get; set; }
        public virtual DbSet<tbl_AgeGroup> tbl_AgeGroup { get; set; }
        public virtual DbSet<tbl_Area> tbl_Area { get; set; }
        public virtual DbSet<tbl_ChildDetails> tbl_ChildDetails { get; set; }
        public virtual DbSet<tbl_CouponCategory> tbl_CouponCategory { get; set; }
        public virtual DbSet<tbl_Discount> tbl_Discount { get; set; }
        public virtual DbSet<tbl_Feedback> tbl_Feedback { get; set; }
        public virtual DbSet<tbl_Holidays> tbl_Holidays { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_OrderType> tbl_OrderType { get; set; }
        public virtual DbSet<tbl_PackageDetails> tbl_PackageDetails { get; set; }
        public virtual DbSet<tbl_ParentDetails> tbl_ParentDetails { get; set; }
        public virtual DbSet<tbl_PaymentDetails> tbl_PaymentDetails { get; set; }
        public virtual DbSet<tbl_PaymentModeType> tbl_PaymentModeType { get; set; }
        public virtual DbSet<tbl_Scheduler> tbl_Scheduler { get; set; }
        public virtual DbSet<tbl_SchoolDetails> tbl_SchoolDetails { get; set; }
    }
}
