//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sCoolMeal2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Discount
    {
        public int DiscountId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<decimal> DiscountAmout { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountedAmountTillDate { get; set; }
        public System.DateTime Validity { get; set; }
        public string CouponDescription { get; set; }
        public Nullable<int> ApplicableCount { get; set; }
        public Nullable<int> IssuedCount { get; set; }
        public Nullable<int> CouponCategory { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbl_CouponCategory tbl_CouponCategory { get; set; }
    }
}
