//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sCoolMeal2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChildDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ChildDetails()
        {
            this.tbl_Order = new HashSet<tbl_Order>();
            this.tbl_Scheduler = new HashSet<tbl_Scheduler>();
        }
    
        public int ChildId { get; set; }
        public int PrimaryParentId { get; set; }
        public Nullable<int> SecondaryParentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public int SchoolId { get; set; }
        public int Standard { get; set; }
        public string Division { get; set; }
        public string HomeAddressId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int IsActive { get; set; }
        public int AgeGroupId { get; set; }
    
        public virtual tbl_AgeGroup tbl_AgeGroup { get; set; }
        public virtual tbl_ParentDetails tbl_ParentDetails { get; set; }
        public virtual tbl_ParentDetails tbl_ParentDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Order> tbl_Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Scheduler> tbl_Scheduler { get; set; }
    }
}
