//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sCoolMeal2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PackageDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PackageDetails()
        {
            this.tbl_Order = new HashSet<tbl_Order>();
        }
    
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string PackageDescription { get; set; }
        public Nullable<int> MealCount { get; set; }
        public Nullable<decimal> WalletAmount { get; set; }
        public Nullable<int> AgeGroupId { get; set; }
        public Nullable<decimal> PerMealCost { get; set; }
        public Nullable<int> Validity { get; set; }
        public Nullable<int> Breakfast { get; set; }
        public Nullable<int> Lunch { get; set; }
        public Nullable<int> EveningSnack { get; set; }
        public Nullable<int> AllDayMeal { get; set; }
        public Nullable<int> Wallet { get; set; }
        public Nullable<int> Tuckshop { get; set; }
    
        public virtual tbl_AgeGroup tbl_AgeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Order> tbl_Order { get; set; }
    }
}
