//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sCoolMeal2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Scheduler
    {
        public int SchedulerId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int MealScheduled { get; set; }
        public Nullable<int> NoOfMealsLeft { get; set; }
        public Nullable<decimal> WalletAmount { get; set; }
        public Nullable<int> Breakfast { get; set; }
        public Nullable<int> Lunch { get; set; }
        public Nullable<int> Snack { get; set; }
        public Nullable<int> MenuId { get; set; }
    
        public virtual tbl_ChildDetails tbl_ChildDetails { get; set; }
        public virtual tbl_Order tbl_Order { get; set; }
    }
}
