//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sCoolMeal2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Feedback
    {
        public int FeedbackId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FeedbackMsg { get; set; }
        public Nullable<int> CanDisplayFeedback { get; set; }
    }
}
