//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sCoolMeal2018
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Holidays
    {
        public int HolidayId { get; set; }
        public int SchoolId { get; set; }
        public Nullable<System.DateTime> HolidayDate { get; set; }
        public string HolidayName { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual tbl_SchoolDetails tbl_SchoolDetails { get; set; }
    }
}
